sudo: required
dist: trusty
language: python

python:
 - 2.7
 - 3.5
 - 3.6

env:
  global:
   - CPLUS_INCLUDE_PATH=/usr/include/gdal
   - C_INCLUDE_PATH=/usr/include/gdal
  matrix:
   - DJANGO_VERSION=1.8.17
   - DJANGO_VERSION=1.9.12
   - DJANGO_VERSION=1.10.5
   - DJANGO_VERSION=1.11.2

install:
 - sudo apt-get update
 - sudo apt-get install -y binutils gdal-bin libgdal1-dev libproj-dev libgeos-dev libspatialite-dev
 - pip install -U setuptools
 - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install pysqlite==2.8.2; fi
 # - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite

   # This is a dependency of our Django quicktest script
 - pip install argparse

 - pip install gdal==1.10.0
 - pip install html5lib==0.999
 - pip install -r requirements.txt

 - pip install coverage

 - pip install flake8

 - python setup.py develop

before_script:
 - flake8
 - pip freeze

script:
 - ./manage.py test
 - coverage run --include="mapentity/*" ./manage.py test

after_success:
 - pip install coveralls
 - coveralls